// 国名（英語）→ 大陸 の対応表。world.geojson の properties.name と一致させること。
const COUNTRY_CONTINENTS = {
  // ── アジア ──────────────────────────────
  "Afghanistan": "Asia",
  "Armenia": "Asia",
  "Azerbaijan": "Asia",
  "Bangladesh": "Asia",
  "Bhutan": "Asia",
  "Brunei": "Asia",
  "Cambodia": "Asia",
  "China": "Asia",
  "Cyprus": "Asia",
  "East Timor": "Asia",
  "Georgia": "Asia",
  "India": "Asia",
  "Indonesia": "Asia",
  "Iran": "Asia",
  "Iraq": "Asia",
  "Israel": "Asia",
  "Japan": "Asia",
  "Jordan": "Asia",
  "Kazakhstan": "Asia",
  "Kuwait": "Asia",
  "Kyrgyzstan": "Asia",
  "Laos": "Asia",
  "Lebanon": "Asia",
  "Malaysia": "Asia",
  "Mongolia": "Asia",
  "Myanmar": "Asia",
  "Nepal": "Asia",
  "North Korea": "Asia",
  "Northern Cyprus": "Asia",
  "Oman": "Asia",
  "Pakistan": "Asia",
  "Philippines": "Asia",
  "Qatar": "Asia",
  "Saudi Arabia": "Asia",
  "South Korea": "Asia",
  "Sri Lanka": "Asia",
  "Syria": "Asia",
  "Taiwan": "Asia",
  "Tajikistan": "Asia",
  "Thailand": "Asia",
  "Turkey": "Asia",
  "Turkmenistan": "Asia",
  "United Arab Emirates": "Asia",
  "Uzbekistan": "Asia",
  "Vietnam": "Asia",
  "West Bank": "Asia",
  "Yemen": "Asia",

  // ── ヨーロッパ ──────────────────────────
  "Albania": "Europe",
  "Austria": "Europe",
  "Belarus": "Europe",
  "Belgium": "Europe",
  "Bosnia and Herzegovina": "Europe",
  "Bulgaria": "Europe",
  "Croatia": "Europe",
  "Czech Republic": "Europe",
  "Denmark": "Europe",
  "England": "Europe",
  "Estonia": "Europe",
  "Finland": "Europe",
  "France": "Europe",
  "Germany": "Europe",
  "Greece": "Europe",
  "Hungary": "Europe",
  "Iceland": "Europe",
  "Ireland": "Europe",
  "Italy": "Europe",
  "Kosovo": "Europe",
  "Latvia": "Europe",
  "Lithuania": "Europe",
  "Luxembourg": "Europe",
  "Macedonia": "Europe",
  "Moldova": "Europe",
  "Montenegro": "Europe",
  "Netherlands": "Europe",
  "Norway": "Europe",
  "Poland": "Europe",
  "Portugal": "Europe",
  "Republic of Serbia": "Europe",
  "Romania": "Europe",
  "Russia": "Europe",
  "Slovakia": "Europe",
  "Slovenia": "Europe",
  "Spain": "Europe",
  "Sweden": "Europe",
  "Switzerland": "Europe",
  "Ukraine": "Europe",

  // ── アフリカ ────────────────────────────
  "Algeria": "Africa",
  "Angola": "Africa",
  "Benin": "Africa",
  "Botswana": "Africa",
  "Burkina Faso": "Africa",
  "Burundi": "Africa",
  "Cameroon": "Africa",
  "Central African Republic": "Africa",
  "Chad": "Africa",
  "Democratic Republic of the Congo": "Africa",
  "Djibouti": "Africa",
  "Egypt": "Africa",
  "Equatorial Guinea": "Africa",
  "Eritrea": "Africa",
  "Ethiopia": "Africa",
  "Gabon": "Africa",
  "Gambia": "Africa",
  "Ghana": "Africa",
  "Guinea": "Africa",
  "Guinea Bissau": "Africa",
  "Ivory Coast": "Africa",
  "Kenya": "Africa",
  "Lesotho": "Africa",
  "Liberia": "Africa",
  "Libya": "Africa",
  "Madagascar": "Africa",
  "Malawi": "Africa",
  "Mali": "Africa",
  "Mauritania": "Africa",
  "Morocco": "Africa",
  "Mozambique": "Africa",
  "Namibia": "Africa",
  "Niger": "Africa",
  "Nigeria": "Africa",
  "Republic of the Congo": "Africa",
  "Rwanda": "Africa",
  "Senegal": "Africa",
  "Sierra Leone": "Africa",
  "Somalia": "Africa",
  "Somaliland": "Africa",
  "South Africa": "Africa",
  "South Sudan": "Africa",
  "Sudan": "Africa",
  "Swaziland": "Africa",
  "Togo": "Africa",
  "Tunisia": "Africa",
  "Uganda": "Africa",
  "United Republic of Tanzania": "Africa",
  "Western Sahara": "Africa",
  "Zambia": "Africa",
  "Zimbabwe": "Africa",

  // ── 北アメリカ ──────────────────────────
  "Belize": "North America",
  "Canada": "North America",
  "Costa Rica": "North America",
  "Cuba": "North America",
  "Dominican Republic": "North America",
  "El Salvador": "North America",
  "Greenland": "North America",
  "Guatemala": "North America",
  "Haiti": "North America",
  "Honduras": "North America",
  "Jamaica": "North America",
  "Mexico": "North America",
  "Nicaragua": "North America",
  "Panama": "North America",
  "Puerto Rico": "North America",
  "The Bahamas": "North America",
  "Trinidad and Tobago": "North America",
  "USA": "North America",

  // ── 南アメリカ ──────────────────────────
  "Argentina": "South America",
  "Bolivia": "South America",
  "Brazil": "South America",
  "Chile": "South America",
  "Colombia": "South America",
  "Ecuador": "South America",
  "Falkland Islands": "South America",
  "Guyana": "South America",
  "Paraguay": "South America",
  "Peru": "South America",
  "Suriname": "South America",
  "Uruguay": "South America",
  "Venezuela": "South America",

  // ── オセアニア ──────────────────────────
  "Australia": "Oceania",
  "Fiji": "Oceania",
  "New Caledonia": "Oceania",
  "New Zealand": "Oceania",
  "Papua New Guinea": "Oceania",
  "Solomon Islands": "Oceania",
  "Vanuatu": "Oceania",

  // ── その他 ──────────────────────────────
  "Antarctica": "Other",
  "French Southern and Antarctic Lands": "Other"
};
